server:
   port: 80

spring:
   application:
      name: cloud-consumer-order

eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
   instance:
      instanceId: order80
      preferIpAddress: true